### signup
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "", 
    "password": "123456",
}

### signin
POST http://localhost:3000/user/signin
Content-Type: application/json

{
    "email": "ahmed6@email.com", 
    "password": "123456"
}

### whoAmI
GET http://localhost:3000/user/whoAmI
Content-Type: application/json

{}

### signout
POST  http://localhost:3000/user/signout
Content-Type: application/json

{}

### Get user by email
GET http://localhost:3000/user?email=ahmed6@email.com
Content-Type: application/json

{}

### Get user by id
GET http://localhost:3000/user/3
Content-Type: application/json

{}

### Update user by id
PATCH  http://localhost:3000/user/3
Content-Type: application/json

{
    "email": "dada@email.com"
}

### Delete user by id
DELETE http://localhost:3000/user/3
Content-Type: application/json

{}